# Generated by Django 5.0.2 on 2024-11-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phonumber', models.IntegerField()),
                ('place', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
