# Generated by Django 5.0.2 on 2024-11-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0003_rename_phoneumber_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_image', models.ImageField(upload_to='waste/')),
            ],
        ),
    ]
